---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-lambda-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  verbs:
  - get
  - list
  - watch
